[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
    .eggs
    | .git
    | .tox
    | .venv
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"  # 使用与 black 兼容的配置
line_length = 120
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
force_sort_within_sections = true